|ERROR|2020-08-11 13:37:55,500|Connection error: Your token is not authorized, please contact admin@fxcm.com
|ERROR|2020-08-11 13:38:27,259|Socket returns unknown error.
|ERROR|2020-08-11 13:38:29,136|Socket returns unknown error.
|ERROR|2020-08-11 13:38:31,985|Socket returns unknown error.
|ERROR|2020-08-11 13:44:52,158|Connection error: Your token is not authorized, please contact admin@fxcm.com
|ERROR|2020-08-11 13:45:07,027|Socket returns unknown error.
|ERROR|2020-08-11 13:55:04,424|Unknown instrument: EURUSD
|ERROR|2020-08-11 14:03:03,175|Socket returns unknown error.
|ERROR|2020-08-11 14:03:03,176|Connection aborted, failed to reconnect
|ERROR|2020-08-12 12:11:18,056|Socket returns unknown error.
|ERROR|2020-08-12 12:11:22,765|Socket returns unknown error.
|ERROR|2020-08-12 13:44:52,882|Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "/root/anaconda3/lib/python3.6/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/root/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/root/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "/root/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 421, in execute_request
    self._abort_queues()
  File "/root/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 636, in _abort_queues
    self._abort_queue(stream)
  File "/root/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 657, in _abort_queue
    self._publish_status('idle', parent=msg)
  File "/root/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 327, in _publish_status
    ident=self._topic('status'),
  File "/root/anaconda3/lib/python3.6/site-packages/jupyter_client/session.py", line 748, in send
    stream.send_multipart(to_send, copy=copy)
  File "/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py", line 262, in send_multipart
    return self.io_thread.send_multipart(*args, **kwargs)
  File "/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py", line 212, in send_multipart
    self.schedule(lambda : self._really_send(*args, **kwargs))
  File "/root/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py", line 203, in schedule
    self._event_pipe.send(b'')
  File "/root/anaconda3/lib/python3.6/site-packages/zmq/sugar/socket.py", line 391, in send
    return super(Socket, self).send(data, flags=flags, copy=copy, track=track)
  File "zmq/backend/cython/socket.pyx", line 727, in zmq.backend.cython.socket.Socket.send
  File "zmq/backend/cython/socket.pyx", line 774, in zmq.backend.cython.socket.Socket.send
  File "zmq/backend/cython/socket.pyx", line 244, in zmq.backend.cython.socket._send_copy
  File "zmq/backend/cython/checkrc.pxd", line 12, in zmq.backend.cython.checkrc._check_rc
KeyboardInterrupt
|ERROR|2020-08-12 13:46:07,167|Socket returns unknown error.
|ERROR|2020-08-12 13:46:07,172|Connection aborted, failed to reconnect
